### ISSUE TITLE
Hero img accordion [JavaScript]

### ISSUE THREAD

**Issue by jakobpalmborg** [mkor92/Uppgift2-Biograf#7]
### In this section we will make the accordion work using JavaScript!

The accordion should scroll automatically after an amount of seconds by default
Add event listeners to the buttons and make it scroll to the next/before "movie".
Add the title, subtitle, button link with javascript for every movie scroll using JS (get the data from a json file)

Dependencies:
- Hero img accordion HTML/CSS

Design:

https://www.figma.com/file/vhNtZfxUiEfTYAYr6yaExM/VadSomHelst?node-id=0%3A1&t=fOSZAsey82JfmXBA-0

**Comment by rfabricioflores** [comment]
https://cdn.discordapp.com/attachments/1054124377983168582/1060198940550627359/Biograf_Lulea_-_Google_Chrome_2023-01-04_15-10-46.mp4
